### PR TITLE
Added proper 1.16.1 support

### PR DESCRIPTION
**Pull request by dries007**
- Fixed 1.16.1 packet definitions by @JLyne  
- including switch_protocol_mode fix
- updated server_chat_room example

So far confirmed working locally. I'll be deploying a build later today to make sure authentication etc still works.

### CODE REVIEW

**Comment by dries007** [comment]
Verified working with MCLink.

@barneygale If you want (and give me the rights) I can make new releases and push them to pypi, or if you'd like it better setup GitHub actions to push to pypi when pushing/merging to master.

**Comment by barneygale** [comment]
Thanks, I have zero IRL time for this right now. You should have merge rights on this repo. Whats your PyPI username?

**Comment by barneygale** [comment]
Worth noting that the chunk format changed in 1.16, and a lot of the existing code will need to be thrown away to make things work sensibly. A task for another time.

**Comment by dries007** [comment]
My username is Dries007 there as well.

Op ma 29 jun. 2020 05:26 schreef Barney Gale <notifications@github.com>:

**Pull request merged**
