### PR TITLE
Add CI

### PR DESCRIPTION
**Pull request by teaearlgraycold**
With regard to #13.

You'll need to add `barneygale/quarry` to Travis CI.

### CODE REVIEW

**Comment by Gjum** [comment]
readme is .rst because it's imported to pypi: https://github.com/barneygale/quarry/blob/master/setup.py#L11

see also https://stackoverflow.com/questions/26737222/pypi-description-markdown-doesnt-work#26737672

**Comment by teaearlgraycold** [comment]
Oh, my bad.

**Comment by barneygale** [comment]
Amazing stuff! As @Gjum says I think the README needs to stay as a `.rst` but otherwise thanks a lot for this

**Comment by barneygale** [comment]
Correct choice of tea by the way, sorry it got cold

**Comment by teaearlgraycold** [comment]
I can fix the readme tomorrow if you want.

On Fri, Feb 17, 2017, 10:26 PM Barney Gale <notifications@github.com> wrote:

Correct choice of tea by the way, sorry it got cold

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/barneygale/quarry/pull/25#issuecomment-280818145>, or mute
the thread

**Comment by teaearlgraycold** [comment]
I finally got around to fixing the readme, all should be good now.

**Comment by williammck** [comment]
This looks great - thanks for fixing the readme! IMO this can be merged in now, unless @barneygale has any other thoughts.

**Comment by teaearlgraycold** [comment]
It turns out that pyopenssl requires a minimum version of 3.3 if you're using Python 3.X, so I changed the supported python versions to "2.7 and 3.3+" in the readme.

**Comment by barneygale** [comment]
Super, thanks!

**Pull request merged**
